@server = https://glowing-couscous-j4q5xwwpw257g5-8080.app.github.dev
###
GET {{server}}/api/instrumentos/2
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "Viento", "descripcion": "Como una flauta"}
###
GET {{server}}/api/musicos
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Joaquín"}



